<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Home</name>
   <tag></tag>
   <elementGuidId>5c8d51e1-5284-421d-b0d8-dfb3133f99f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appGoesHere']/div/div[2]/div/div[2]/div[3]/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Home&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>83fa89df-398c-4ccd-ac14-7397760982b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>42bec2ee-104f-4b47-9499-8ab5ca4e524f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appGoesHere&quot;)/div[@class=&quot;top-level-ui-view ng-scope&quot;]/div[@class=&quot;navbar&quot;]/div[@class=&quot;navbar-inner ng-scope&quot;]/div[@class=&quot;navbar-container ng-scope&quot;]/div[@class=&quot;header-title&quot;]/h1[1]</value>
      <webElementGuid>3d1ae4a5-9918-4935-b6e2-0690268c0c65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appGoesHere']/div/div[2]/div/div[2]/div[3]/h1</value>
      <webElementGuid>2172961d-04e2-4a4f-b8ac-8524c37c06cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 1996-2024'])[1]/preceding::h1[1]</value>
      <webElementGuid>81bfaffb-18bf-48e9-9a55-5d7cab2f67ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>85713401-ca3c-488b-8009-a1ecc12beed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>875b1b33-942b-4eff-995f-a281a1a9d5c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
