<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5ab33e2f-31e4-4bfe-a372-ace2cd4fdeff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appGoesHere']/div/div[2]/div/div[2]/div/a/small/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.navbar-brand</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d8eeb6a7-d8dc-4001-94fe-2c552cd1c47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/img/logo.png</value>
      <webElementGuid>d0d571b5-5da2-45d4-a68e-bc7109bd106b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appGoesHere&quot;)/div[@class=&quot;top-level-ui-view ng-scope&quot;]/div[@class=&quot;navbar&quot;]/div[@class=&quot;navbar-inner ng-scope&quot;]/div[@class=&quot;navbar-container ng-scope&quot;]/div[@class=&quot;navbar-header pull-left&quot;]/a[@class=&quot;navbar-brand&quot;]/small[1]/img[1]</value>
      <webElementGuid>82f68b87-80f5-4112-bbfd-6605afbccd40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appGoesHere']/div/div[2]/div/div[2]/div/a/small/img</value>
      <webElementGuid>4fcd3771-5f26-4163-ac52-39407c103887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d45ef4e5-c1ea-4b21-ba01-4f047bd560fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/img/logo.png']</value>
      <webElementGuid>ef231eac-d5bc-438c-82a3-65cda6c4ba80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
