<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NONE</name>
   <tag></tag>
   <elementGuidId>8aa22d8f-20ec-4aa0-9f59-68f0477e0a1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='canvas_header']/div[2]/div/div[3]/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-group.pull-left.open > ul.dropdown-menu.dropdown-blue.pull-left > li.ng-scope > a.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Select Holdout Type&quot;i] >> internal:role=list >> internal:role=link[name=&quot;NONE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fee45012-9d04-4729-89e0-c6e511780b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>9e511cce-440d-4371-a108-eca0cbacb2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>onCampaignHoldoutClicked(campaign_holdout)</value>
      <webElementGuid>3104b389-a4ab-4c1d-80a2-bdedc3c30026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>edd4d35b-e3a2-47cf-b32c-c58c91399315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>8b22b44d-ad2a-4975-9bc6-d886c96798aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;canvas_header&quot;)/div[@class=&quot;row&quot;]/div[1]/div[@class=&quot;btn-group pull-left open&quot;]/ul[@class=&quot;dropdown-menu dropdown-blue pull-left&quot;]/li[@class=&quot;ng-scope&quot;]/a[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>d4a31f75-634e-4857-8dc6-381f1d2cdcfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='canvas_header']/div[2]/div/div[3]/ul/li[3]/a</value>
      <webElementGuid>7c5af4ef-07f0-4cb2-8654-f6846d18bc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'NONE')])[2]</value>
      <webElementGuid>5eda6a0c-d894-4d79-bd70-a3a6c064b9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holdout Type'])[1]/following::a[1]</value>
      <webElementGuid>a62aeaf6-ea30-48e9-b031-e32cc08a009b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NONE'])[1]/following::a[2]</value>
      <webElementGuid>e24005f4-6bad-4cea-932a-eee78024772c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLOBAL'])[1]/preceding::a[1]</value>
      <webElementGuid>df1ffce6-99c5-499e-b126-82fbe35ad189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATA'])[1]/preceding::a[2]</value>
      <webElementGuid>e0ce0c15-eccf-433c-bb98-70595ed52448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[48]</value>
      <webElementGuid>885a2e66-caa8-4d5a-86cb-a023b8df9eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[3]/a</value>
      <webElementGuid>838b6547-9f69-4fd7-8f0a-c0afc42bd447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'NONE' or . = 'NONE')]</value>
      <webElementGuid>caceddd8-c01f-4acb-9f22-2fd5a47a7d26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
