<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>js-plumb-canvas_Sample_panzoom-wrapper</name>
   <tag></tag>
   <elementGuidId>7e56e672-6119-48b0-b76c-94e03ed6bafc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//js-plumb-canvas[@id='panzoom-wrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#panzoom-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#panzoom-wrapper</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>js-plumb-canvas</value>
      <webElementGuid>7dc01f5c-e574-4d52-83e6-f256250ab2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>plumb</name>
      <type>Main</type>
      <value>jsPlumb.instance</value>
      <webElementGuid>5c403b79-e42a-4d58-b4d6-809bd16f5c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>panzoom-wrapper</value>
      <webElementGuid>3f685d94-9917-43a4-8a3d-ee30be833c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>connect</name>
      <type>Main</type>
      <value>onConnection</value>
      <webElementGuid>bbe03040-0a8a-43c9-a81e-5a15d0e35b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disconnect</name>
      <type>Main</type>
      <value>onDisconnect</value>
      <webElementGuid>ade06a0a-249b-4bb0-91ae-2acd6775aa3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>moved</name>
      <type>Main</type>
      <value>onConnectionMoved</value>
      <webElementGuid>3c803f2a-b6ea-4d3b-99cd-dedb890e05b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>click</name>
      <type>Main</type>
      <value>onConnectionClick</value>
      <webElementGuid>a7cc810a-708b-4fda-8369-7a5c055c6eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dblclick</name>
      <type>Main</type>
      <value>onConnectionDblclick</value>
      <webElementGuid>eec91421-7d9a-47b4-a194-3541bc4a6e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>endpointclick</name>
      <type>Main</type>
      <value>onEndpointClick</value>
      <webElementGuid>f21cfa36-5f16-481f-8fc3-0f4763f70548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>endpointdblclick</name>
      <type>Main</type>
      <value>onEndpointDblClick</value>
      <webElementGuid>08447f54-bff4-4763-a50d-ff0e1c3a7483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>beforedrop</name>
      <type>Main</type>
      <value>onBeforeDrop</value>
      <webElementGuid>a37e6765-e7c3-49d8-aa85-9aff53a2c27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contextmenu</name>
      <type>Main</type>
      <value>onConnectionRightClick</value>
      <webElementGuid>ed6bc5ba-13d1-415f-8330-bc5563ed522d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>8accb8ce-d9a4-4f66-a954-e6534c845d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>y</value>
      <webElementGuid>b412c41a-deb9-4737-a1ae-e0bd38848eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zoom</name>
      <type>Main</type>
      <value>zoom</value>
      <webElementGuid>0af3147b-6d6f-4529-b088-f2a178132779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>panallowed</name>
      <type>Main</type>
      <value>panAllowed</value>
      <webElementGuid>f7d484fd-f9c3-499c-923a-dc996df8069b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pantoggle</name>
      <type>Main</type>
      <value>panModeToggle</value>
      <webElementGuid>e1d7944b-2b91-4040-9af8-f060ee51b0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overlays</name>
      <type>Main</type>
      <value>connectionOverlays</value>
      <webElementGuid>20f21acf-b886-456a-8516-12996e84b0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-isolate-scope ui-draggable ui-draggable-handle</value>
      <webElementGuid>171bde02-d8b1-440c-a701-17edc5ccdd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panzoom-wrapper&quot;)</value>
      <webElementGuid>f23d2e56-9e6e-4adc-9184-86286b159514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//js-plumb-canvas[@id='panzoom-wrapper']</value>
      <webElementGuid>9a4271a0-8d3b-40c3-96ef-b12e7662d80c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panzoom-wrapper_parent']/js-plumb-canvas</value>
      <webElementGuid>8e9710cd-f3b9-42f1-973a-d13c5a00a551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sample'])[1]/following::js-plumb-canvas[1]</value>
      <webElementGuid>59c3e9cc-341f-407b-8429-74c26ba123a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Split'])[1]/following::js-plumb-canvas[1]</value>
      <webElementGuid>df019b8c-d01d-4af8-a6db-411796baccf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//js-plumb-canvas</value>
      <webElementGuid>79ca830d-dcd7-4dac-9766-41524c65e026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//js-plumb-canvas[@id = 'panzoom-wrapper']</value>
      <webElementGuid>e75b9b61-a1bf-4582-ad85-91b7a29c2e33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
