<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_PM_clockpicker-canvas-fg</name>
   <tag></tag>
   <elementGuidId>8962dd09-4021-4ec1-ad8d-22667847cd87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>circle.clockpicker-canvas-fg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>circle >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>5a76a028-0931-4b0f-8a5c-fd9adca35f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clockpicker-canvas-fg</value>
      <webElementGuid>dc527bc6-fdb0-4ce5-a1b8-07a57ba02ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>3.5</value>
      <webElementGuid>0c33aa7a-772b-41a4-994d-647d71f2b35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>39.99999999999999</value>
      <webElementGuid>0e6b07d9-ddde-485a-b202-5ce4479058b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>-69.2820323027551</value>
      <webElementGuid>6affeb0b-cf71-434f-be8f-206e126106b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;popover clockpicker-popover bottom clockpicker-align-left&quot;]/div[@class=&quot;popover-content&quot;]/div[@class=&quot;clockpicker-plate&quot;]/div[@class=&quot;clockpicker-canvas&quot;]/svg[@class=&quot;clockpicker-svg&quot;]/g[1]/circle[@class=&quot;clockpicker-canvas-fg&quot;]</value>
      <webElementGuid>543840bb-8c6f-4796-ae93-37b00730802f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
