<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_On what date and time should the cycl_01a8fa</name>
   <tag></tag>
   <elementGuidId>6e63df4e-f37a-4da1-a823-99aa192b83d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='startDateAndTime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;startDateAndTime&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Select a Date&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c0e55ac-890d-40b4-8f0c-3b73d6cd9b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startDateAndTime</value>
      <webElementGuid>4bf7437b-9d74-4a24-9ce3-65c39b9596d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date-picker ng-pristine ng-untouched ng-valid ng-isolate-scope</value>
      <webElementGuid>6523f0be-a0a2-459f-934e-dd4531e67225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select a Date</value>
      <webElementGuid>bab9088f-0909-4da0-a11f-374beef2e37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba32e770-9e1f-4039-9add-509be9e229b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>holder.start_date</value>
      <webElementGuid>b9db98e0-9d1d-44ad-8b0d-a6e736a186d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>options</name>
      <type>Main</type>
      <value>start_date_picker_options</value>
      <webElementGuid>cd81a955-60b7-4898-9c68-7b79ca943864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal fade ng-isolate-scope modal-message modal-info modal-message-lg in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body ng-scope&quot;]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse&quot;]/div[@class=&quot;control-group&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;col-lg-12 col-sm-12 col-xs-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control date-picker ng-pristine ng-untouched ng-valid ng-isolate-scope&quot;]</value>
      <webElementGuid>c3f5394c-ad78-4ef8-a1c8-3e78fa33b0ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='startDateAndTime']</value>
      <webElementGuid>ebae6e6e-b67a-4a38-bc28-5bdd696c7449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>5cff83e8-c9db-4456-bcf2-4f0d90250cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'startDateAndTime' and @placeholder = 'Select a Date' and @type = 'text']</value>
      <webElementGuid>a36b69ff-5ba7-40c2-abf6-484a1d76a788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
